export const LOG_OUT = 'LOG_OUT'
export const UPDATE_DETAILS = 'UPDATE_DETAILS'
export const SET_RESULTS = 'SET_RESULTS'
export const LOAD_QUESTIONAIRE = 'LOAD_QUESTIONAIRE'
export const CREATE_QUESTIONNAIRE = 'CREATE_QUESTIONNAIRE'
export const UPDATE_QUESTIONNAIRE = 'UPDATE_QUESTIONNAIRE'
export const UI_START_LOADING = 'UI_START_LOADING'
export const UI_STOP_LOADING = 'UI_STOP_LOADING'

